name: 'ci'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.16' ]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Restore Cache
      uses: actions/cache@v2
      id: cache
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - run: mkdir -p ~/.config/equinix
    - run: touch ~/.config/equinix/metal.yaml
    - name: Build docs
      run: make generate-docs
      env:
        METAL_AUTH_TOKEN: bogus
    - name: Detect Uncommitted Docs
      run: git diff --exit-code docs
